### ISSUE TITLE
Fails on specific video

### ISSUE THREAD

**Issue by rangerscience** [iphoting/youtube-dl-api-server-heroku#1]
This one: https://www.youtube.com/watch?v=mvl0lcybPQ4

Found during a pair session with a co-worker - I don't know what's special about this video that it causes the failure, but I thought you should know.

Steps:
1) Followed ReadMe to setup
2) `heroku run bash`
3) `youtube-dl https://www.youtube.com/watch?v=mvl0lcybPQ4`

Error:
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1057, in _decrypt_signature
    video_id, player_url, s
  File "/app/.heroku/python/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 971, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/app/.heroku/python/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 519, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/app/.heroku/python/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 426, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/app/.heroku/python/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 406, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/app/.heroku/python/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/app/.heroku/python/lib/python2.7/urllib2.py", line 421, in open
    protocol = req.get_type()
  File "/app/.heroku/python/lib/python2.7/urllib2.py", line 283, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: /yts/jsbin/player-en_US-vfl8LqiZp/base.js
 (caused by ValueError(u'unknown url type: /yts/jsbin/player-en_US-vfl8LqiZp/base.js',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by iphoting** [comment]
I haven't had time to test this URL out, but does it work with your local copy of YouTube-dl? and which version?
